[2023-01-26T14:46:47.003+0000] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:46:47.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:46:47.008+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:46:47.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:46:47.086+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:46:47.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:46:47.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:46:47.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.136 seconds
[2023-01-26T14:47:17.656+0000] {processor.py:153} INFO - Started process (PID=130) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:17.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:47:17.660+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:47:17.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:17.745+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:47:17.732+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:47:17.751+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:17.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.122 seconds
[2023-01-26T14:47:48.627+0000] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:48.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:47:48.631+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:47:48.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:48.693+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:47:48.684+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:47:48.697+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:47:48.719+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.093 seconds
[2023-01-26T14:48:18.910+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:18.932+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:48:18.935+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:48:18.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:19.397+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:48:19.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:48:19.441+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:19.467+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.559 seconds
[2023-01-26T14:48:50.083+0000] {processor.py:153} INFO - Started process (PID=282) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:50.085+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:48:50.086+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:48:50.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:50.126+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:48:50.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:48:50.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:48:50.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.069 seconds
[2023-01-26T14:49:20.558+0000] {processor.py:153} INFO - Started process (PID=346) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:20.561+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:49:20.563+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:49:20.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:20.653+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:49:20.642+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:49:20.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:20.683+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.129 seconds
[2023-01-26T14:49:51.025+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:51.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:49:51.030+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:49:51.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:51.090+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:49:51.079+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:49:51.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:49:51.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.090 seconds
[2023-01-26T14:50:21.230+0000] {processor.py:153} INFO - Started process (PID=454) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:21.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:50:21.233+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:50:21.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:21.285+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:50:21.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:50:21.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:21.312+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-01-26T14:50:51.582+0000] {processor.py:153} INFO - Started process (PID=499) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:51.584+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:50:51.585+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:50:51.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:51.630+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:50:51.621+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:50:51.634+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:50:51.650+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.070 seconds
[2023-01-26T14:51:22.098+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:22.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:51:22.101+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:51:22.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:22.172+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:51:22.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:51:22.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:22.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.102 seconds
[2023-01-26T14:51:52.732+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:52.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:51:52.736+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:51:52.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:52.798+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:51:52.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:51:52.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:51:52.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.091 seconds
[2023-01-26T14:52:23.070+0000] {processor.py:153} INFO - Started process (PID=671) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:52:23.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T14:52:23.077+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:52:23.077+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:52:23.180+0000] {logging_mixin.py:137} INFO - [2023-01-26T14:52:23.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T14:52:23.187+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T14:52:23.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.150 seconds
[2023-01-26T20:44:10.908+0000] {processor.py:153} INFO - Started process (PID=62) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:10.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:44:10.912+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:44:10.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:11.088+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:44:11.068+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:44:11.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:11.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.229 seconds
[2023-01-26T20:44:41.392+0000] {processor.py:153} INFO - Started process (PID=105) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:41.393+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:44:41.395+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:44:41.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:41.435+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:44:41.426+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:44:41.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:44:41.458+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.068 seconds
[2023-01-26T20:45:12.320+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:12.322+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:45:12.323+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:45:12.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:12.369+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:45:12.358+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:45:12.373+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:12.391+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.073 seconds
[2023-01-26T20:45:43.255+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:43.257+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:45:43.257+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:45:43.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:43.296+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:45:43.288+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:45:43.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:45:43.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.062 seconds
[2023-01-26T20:46:14.030+0000] {processor.py:153} INFO - Started process (PID=261) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:14.032+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:46:14.033+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:46:14.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:14.091+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:46:14.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:46:14.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:14.114+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.086 seconds
[2023-01-26T20:46:44.353+0000] {processor.py:153} INFO - Started process (PID=326) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:44.356+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:46:44.357+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:46:44.357+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:44.411+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:46:44.400+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:46:44.416+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:46:44.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.082 seconds
[2023-01-26T20:47:14.564+0000] {processor.py:153} INFO - Started process (PID=369) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:14.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:47:14.568+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:47:14.568+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:14.609+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:47:14.602+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:47:14.614+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:14.629+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.068 seconds
[2023-01-26T20:47:44.870+0000] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:44.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:47:44.875+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:47:44.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:44.910+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:47:44.904+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:47:44.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:47:44.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.061 seconds
[2023-01-26T20:48:14.987+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:14.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:48:14.990+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:48:14.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:15.024+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:48:15.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:48:15.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:15.043+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.057 seconds
[2023-01-26T20:48:45.137+0000] {processor.py:153} INFO - Started process (PID=542) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:45.139+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:48:45.140+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:48:45.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:45.187+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:48:45.180+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:48:45.189+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:48:45.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.069 seconds
[2023-01-26T20:49:15.282+0000] {processor.py:153} INFO - Started process (PID=586) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:15.284+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:49:15.285+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:49:15.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:15.328+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:49:15.321+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:49:15.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:15.345+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.064 seconds
[2023-01-26T20:49:46.100+0000] {processor.py:153} INFO - Started process (PID=650) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:46.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:49:46.103+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:49:46.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:46.149+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:49:46.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:49:46.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:49:46.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.069 seconds
[2023-01-26T20:50:16.936+0000] {processor.py:153} INFO - Started process (PID=694) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:16.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:50:16.940+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:50:16.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:16.978+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:50:16.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:50:16.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:16.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.064 seconds
[2023-01-26T20:50:47.646+0000] {processor.py:153} INFO - Started process (PID=758) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:47.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:50:47.648+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:50:47.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:47.705+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:50:47.695+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:50:47.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:50:47.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.084 seconds
[2023-01-26T20:51:17.863+0000] {processor.py:153} INFO - Started process (PID=802) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:17.865+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:51:17.866+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:51:17.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:17.916+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:51:17.907+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:51:17.920+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:17.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.075 seconds
[2023-01-26T20:51:48.727+0000] {processor.py:153} INFO - Started process (PID=866) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:48.728+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-01-26T20:51:48.730+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:51:48.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:48.766+0000] {logging_mixin.py:137} INFO - [2023-01-26T20:51:48.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-01-26T20:51:48.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-01-26T20:51:48.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.061 seconds
