[2023-04-24T21:42:29.934+0000] {processor.py:153} INFO - Started process (PID=66) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:42:29.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:42:29.940+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:42:29.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:42:30.046+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:42:30.028+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:42:30.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:42:30.087+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.157 seconds
[2023-04-24T21:43:00.267+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:00.271+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:43:00.272+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:43:00.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:00.357+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:43:00.341+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:43:00.363+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:00.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.125 seconds
[2023-04-24T21:43:30.491+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:30.495+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:43:30.496+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:43:30.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:30.566+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:43:30.552+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:43:30.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:43:30.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.127 seconds
[2023-04-24T21:44:00.707+0000] {processor.py:153} INFO - Started process (PID=217) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:00.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:44:00.710+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:44:00.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:00.751+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:44:00.744+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:44:00.754+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:00.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.067 seconds
[2023-04-24T21:44:31.360+0000] {processor.py:153} INFO - Started process (PID=285) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:31.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:44:31.366+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:44:31.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:31.432+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:44:31.419+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:44:31.437+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:44:31.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.102 seconds
[2023-04-24T21:45:02.048+0000] {processor.py:153} INFO - Started process (PID=329) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:02.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:45:02.052+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:45:02.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:02.093+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:45:02.086+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:45:02.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:02.116+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.072 seconds
[2023-04-24T21:45:32.755+0000] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:32.758+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:45:32.759+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:45:32.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:32.849+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:45:32.835+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:45:32.855+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:45:32.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.127 seconds
[2023-04-24T21:46:03.523+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:03.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:46:03.528+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:46:03.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:03.608+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:46:03.595+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:46:03.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:03.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.116 seconds
[2023-04-24T21:46:34.236+0000] {processor.py:153} INFO - Started process (PID=510) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:34.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:46:34.239+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:46:34.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:34.323+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:46:34.309+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:46:34.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:46:34.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.207 seconds
[2023-04-24T21:47:04.835+0000] {processor.py:153} INFO - Started process (PID=555) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:04.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:47:04.838+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:47:04.837+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:04.871+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:47:04.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:47:04.874+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:04.891+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.059 seconds
[2023-04-24T21:47:35.804+0000] {processor.py:153} INFO - Started process (PID=619) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:35.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:47:35.809+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:47:35.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:35.884+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:47:35.873+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:47:35.889+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:47:35.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.110 seconds
[2023-04-24T21:48:06.566+0000] {processor.py:153} INFO - Started process (PID=663) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:06.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:48:06.569+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:48:06.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:06.610+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:48:06.601+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:48:06.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:06.674+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.111 seconds
[2023-04-24T21:48:36.792+0000] {processor.py:153} INFO - Started process (PID=728) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:36.794+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:48:36.795+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:48:36.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:36.836+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:48:36.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:48:36.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:48:36.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.075 seconds
[2023-04-24T21:49:07.620+0000] {processor.py:153} INFO - Started process (PID=781) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:07.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:49:07.623+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:49:07.623+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:07.672+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:49:07.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:49:07.683+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:07.703+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-04-24T21:49:38.072+0000] {processor.py:153} INFO - Started process (PID=836) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:38.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:49:38.075+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:49:38.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:38.116+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:49:38.107+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:49:38.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:49:38.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.067 seconds
[2023-04-24T21:50:08.782+0000] {processor.py:153} INFO - Started process (PID=902) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:08.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:50:08.786+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:50:08.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:08.868+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:50:08.852+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:50:08.874+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:08.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.123 seconds
[2023-04-24T21:50:39.492+0000] {processor.py:153} INFO - Started process (PID=944) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:39.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:50:39.495+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:50:39.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:39.543+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:50:39.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:50:39.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:50:39.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.077 seconds
[2023-04-24T21:51:10.151+0000] {processor.py:153} INFO - Started process (PID=997) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:10.154+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:51:10.156+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:51:10.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:10.223+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:51:10.209+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:51:10.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:10.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.103 seconds
[2023-04-24T21:51:40.576+0000] {processor.py:153} INFO - Started process (PID=1053) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:40.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:51:40.579+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:51:40.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:40.648+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:51:40.635+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:51:40.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:51:40.681+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.108 seconds
[2023-04-24T21:52:10.895+0000] {processor.py:153} INFO - Started process (PID=1096) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:10.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:52:10.897+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:52:10.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:10.959+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:52:10.948+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:52:10.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:10.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-24T21:52:41.260+0000] {processor.py:153} INFO - Started process (PID=1159) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:41.263+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:52:41.267+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:52:41.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:41.336+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:52:41.324+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:52:41.340+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:52:41.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-24T21:53:11.591+0000] {processor.py:153} INFO - Started process (PID=1203) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:11.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:53:11.594+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:53:11.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:11.692+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:53:11.675+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:53:11.700+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:11.720+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.132 seconds
[2023-04-24T21:53:42.082+0000] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:42.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:53:42.084+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:53:42.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:42.129+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:53:42.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:53:42.132+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:53:42.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.080 seconds
[2023-04-24T21:54:12.791+0000] {processor.py:153} INFO - Started process (PID=1320) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:12.793+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:54:12.794+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:54:12.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:12.858+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:54:12.846+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:54:12.863+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:12.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-24T21:54:43.462+0000] {processor.py:153} INFO - Started process (PID=1375) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:43.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:54:43.466+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:54:43.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:43.507+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:54:43.499+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:54:43.511+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:54:43.550+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.091 seconds
[2023-04-24T21:55:14.251+0000] {processor.py:153} INFO - Started process (PID=1439) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:14.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:55:14.254+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:55:14.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:14.329+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:55:14.313+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:55:14.334+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:14.354+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.107 seconds
[2023-04-24T21:55:44.995+0000] {processor.py:153} INFO - Started process (PID=1484) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:44.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:55:44.999+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:55:44.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:45.062+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:55:45.052+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:55:45.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:55:45.085+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.093 seconds
[2023-04-24T21:56:15.624+0000] {processor.py:153} INFO - Started process (PID=1548) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:15.626+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:56:15.627+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:56:15.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:15.675+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:56:15.669+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:56:15.678+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:15.697+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.076 seconds
[2023-04-24T21:56:45.769+0000] {processor.py:153} INFO - Started process (PID=1592) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:45.771+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:56:45.772+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:56:45.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:45.840+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:56:45.828+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:56:45.845+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:56:45.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-24T21:57:15.995+0000] {processor.py:153} INFO - Started process (PID=1656) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:15.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:57:15.998+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:57:15.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:16.039+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:57:16.032+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:57:16.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:16.060+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.068 seconds
[2023-04-24T21:57:46.408+0000] {processor.py:153} INFO - Started process (PID=1700) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:46.409+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:57:46.410+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:57:46.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:46.471+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:57:46.463+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:57:46.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:57:46.491+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.086 seconds
[2023-04-24T21:58:17.241+0000] {processor.py:153} INFO - Started process (PID=1763) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:17.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:58:17.246+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:58:17.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:17.328+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:58:17.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:58:17.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:17.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.129 seconds
[2023-04-24T21:58:47.557+0000] {processor.py:153} INFO - Started process (PID=1806) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:47.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:58:47.560+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:58:47.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:47.637+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:58:47.625+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:58:47.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:58:47.662+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.109 seconds
[2023-04-24T21:59:17.872+0000] {processor.py:153} INFO - Started process (PID=1872) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:17.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:59:17.875+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:59:17.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:17.915+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:59:17.908+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:59:17.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:17.937+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.067 seconds
[2023-04-24T21:59:48.642+0000] {processor.py:153} INFO - Started process (PID=1916) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:48.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T21:59:48.646+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:59:48.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:48.684+0000] {logging_mixin.py:137} INFO - [2023-04-24T21:59:48.677+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T21:59:48.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T21:59:48.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.067 seconds
[2023-04-24T22:00:19.418+0000] {processor.py:153} INFO - Started process (PID=1980) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:19.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:00:19.426+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:00:19.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:19.485+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:00:19.474+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:00:19.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:19.513+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.098 seconds
[2023-04-24T22:00:50.081+0000] {processor.py:153} INFO - Started process (PID=2033) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:50.084+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:00:50.086+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:00:50.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:50.158+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:00:50.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:00:50.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:00:50.192+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.115 seconds
[2023-04-24T22:01:20.429+0000] {processor.py:153} INFO - Started process (PID=2088) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:20.431+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:01:20.432+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:01:20.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:20.484+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:01:20.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:01:20.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:20.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.079 seconds
[2023-04-24T22:01:50.639+0000] {processor.py:153} INFO - Started process (PID=2141) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:50.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:01:50.642+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:01:50.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:50.689+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:01:50.681+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:01:50.693+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:01:50.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.077 seconds
[2023-04-24T22:02:20.806+0000] {processor.py:153} INFO - Started process (PID=2196) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:20.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:02:20.809+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:02:20.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:20.851+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:02:20.844+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:02:20.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:20.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.071 seconds
[2023-04-24T22:02:51.334+0000] {processor.py:153} INFO - Started process (PID=2260) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:51.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:02:51.338+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:02:51.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:51.405+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:02:51.394+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:02:51.411+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:02:51.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-24T22:03:21.597+0000] {processor.py:153} INFO - Started process (PID=2304) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:21.599+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:03:21.600+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:03:21.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:21.636+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:03:21.630+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:03:21.640+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:21.658+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.064 seconds
[2023-04-24T22:03:51.794+0000] {processor.py:153} INFO - Started process (PID=2368) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:51.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:03:51.797+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:03:51.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:51.863+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:03:51.852+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:03:51.869+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:03:51.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.098 seconds
[2023-04-24T22:04:22.765+0000] {processor.py:153} INFO - Started process (PID=2412) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:22.767+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:04:22.767+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:04:22.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:22.812+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:04:22.805+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:04:22.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:22.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.106 seconds
[2023-04-24T22:04:53.412+0000] {processor.py:153} INFO - Started process (PID=2476) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:53.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:04:53.424+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:04:53.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:53.471+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:04:53.464+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:04:53.476+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:04:53.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.086 seconds
[2023-04-24T22:05:24.095+0000] {processor.py:153} INFO - Started process (PID=2519) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:24.096+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:05:24.097+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:05:24.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:24.136+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:05:24.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:05:24.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:24.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.065 seconds
[2023-04-24T22:05:54.707+0000] {processor.py:153} INFO - Started process (PID=2582) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:54.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:05:54.710+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:05:54.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:54.755+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:05:54.746+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:05:54.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:05:54.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.073 seconds
[2023-04-24T22:06:25.426+0000] {processor.py:153} INFO - Started process (PID=2626) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:25.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:06:25.428+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:06:25.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:25.482+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:06:25.474+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:06:25.485+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:25.506+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.083 seconds
[2023-04-24T22:06:55.782+0000] {processor.py:153} INFO - Started process (PID=2689) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:55.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:06:55.787+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:06:55.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:55.848+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:06:55.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:06:55.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:06:55.872+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.092 seconds
[2023-04-24T22:07:26.486+0000] {processor.py:153} INFO - Started process (PID=2733) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:26.489+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:07:26.490+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:07:26.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:26.559+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:07:26.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:07:26.562+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:26.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-24T22:07:56.907+0000] {processor.py:153} INFO - Started process (PID=2797) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:56.909+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:07:56.910+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:07:56.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:56.966+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:07:56.955+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:07:56.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:07:56.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-04-24T22:08:27.631+0000] {processor.py:153} INFO - Started process (PID=2860) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:27.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:08:27.636+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:08:27.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:27.694+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:08:27.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:08:27.697+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:27.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.089 seconds
[2023-04-24T22:08:58.186+0000] {processor.py:153} INFO - Started process (PID=2904) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:58.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:08:58.188+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:08:58.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:58.225+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:08:58.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:08:58.228+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:08:58.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.064 seconds
[2023-04-24T22:09:28.836+0000] {processor.py:153} INFO - Started process (PID=2968) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:09:28.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-24T22:09:28.840+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:09:28.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:09:28.919+0000] {logging_mixin.py:137} INFO - [2023-04-24T22:09:28.907+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-24T22:09:28.925+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-24T22:09:28.945+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.112 seconds
