[2023-04-21T22:11:09.723+0000] {processor.py:153} INFO - Started process (PID=67) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:09.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:11:09.728+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:11:09.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:09.807+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:11:09.790+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:11:09.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:09.842+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.124 seconds
[2023-04-21T22:11:40.392+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:40.395+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:11:40.396+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:11:40.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:40.483+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:11:40.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:11:40.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:11:40.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.129 seconds
[2023-04-21T22:12:11.261+0000] {processor.py:153} INFO - Started process (PID=176) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:11.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:12:11.267+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:12:11.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:11.408+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:12:11.387+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:12:11.422+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:11.464+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.206 seconds
[2023-04-21T22:12:41.724+0000] {processor.py:153} INFO - Started process (PID=220) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:41.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:12:41.815+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:12:41.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:41.924+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:12:41.887+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:12:41.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:12:41.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.236 seconds
[2023-04-21T22:13:12.372+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:12.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:13:12.377+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:13:12.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:12.460+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:13:12.447+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:13:12.465+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:12.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.118 seconds
[2023-04-21T22:13:42.866+0000] {processor.py:153} INFO - Started process (PID=329) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:42.872+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:13:42.873+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:13:42.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:42.954+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:13:42.943+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:13:42.958+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:13:42.981+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.120 seconds
[2023-04-21T22:14:13.092+0000] {processor.py:153} INFO - Started process (PID=373) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:13.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:14:13.099+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:14:13.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:13.173+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:14:13.166+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:14:13.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:13.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.108 seconds
[2023-04-21T22:14:43.424+0000] {processor.py:153} INFO - Started process (PID=437) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:43.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:14:43.429+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:14:43.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:43.504+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:14:43.492+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:14:43.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:14:43.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.106 seconds
[2023-04-21T22:15:13.840+0000] {processor.py:153} INFO - Started process (PID=481) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:13.846+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:15:13.848+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:15:13.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:13.913+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:15:13.900+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:15:13.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:13.934+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.097 seconds
[2023-04-21T22:15:44.436+0000] {processor.py:153} INFO - Started process (PID=544) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:44.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:15:44.443+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:15:44.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:44.571+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:15:44.556+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:15:44.580+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:15:44.613+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.179 seconds
[2023-04-21T22:16:15.273+0000] {processor.py:153} INFO - Started process (PID=588) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:15.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:16:15.278+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:16:15.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:15.347+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:16:15.336+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:16:15.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:15.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-21T22:16:45.610+0000] {processor.py:153} INFO - Started process (PID=632) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:45.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:16:45.613+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:16:45.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:45.678+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:16:45.669+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:16:45.681+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:16:45.701+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.094 seconds
[2023-04-21T22:17:16.141+0000] {processor.py:153} INFO - Started process (PID=697) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:16.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:17:16.145+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:17:16.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:16.202+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:17:16.190+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:17:16.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:16.224+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-04-21T22:17:46.503+0000] {processor.py:153} INFO - Started process (PID=741) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:46.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:17:46.508+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:17:46.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:46.582+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:17:46.570+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:17:46.587+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:17:46.603+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.104 seconds
[2023-04-21T22:18:16.863+0000] {processor.py:153} INFO - Started process (PID=805) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:16.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:18:16.868+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:18:16.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:16.989+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:18:16.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:18:16.997+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:17.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.159 seconds
[2023-04-21T22:18:47.770+0000] {processor.py:153} INFO - Started process (PID=849) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:47.772+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:18:47.773+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:18:47.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:47.848+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:18:47.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:18:47.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:18:47.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.103 seconds
[2023-04-21T22:19:17.989+0000] {processor.py:153} INFO - Started process (PID=912) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:17.991+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:19:17.993+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:19:17.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:18.064+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:19:18.050+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:19:18.070+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:18.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.107 seconds
[2023-04-21T22:19:48.383+0000] {processor.py:153} INFO - Started process (PID=956) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:48.387+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:19:48.388+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:19:48.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:48.548+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:19:48.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:19:48.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:19:48.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.190 seconds
[2023-04-21T22:20:18.966+0000] {processor.py:153} INFO - Started process (PID=1000) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:18.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:20:18.970+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:20:18.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:19.046+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:20:19.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:20:19.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:19.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.111 seconds
[2023-04-21T22:20:49.910+0000] {processor.py:153} INFO - Started process (PID=1064) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:49.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:20:49.914+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:20:49.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:49.975+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:20:49.965+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:20:49.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:20:49.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.090 seconds
[2023-04-21T22:21:20.663+0000] {processor.py:153} INFO - Started process (PID=1108) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:20.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:21:20.668+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:21:20.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:20.737+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:21:20.722+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:21:20.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:20.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.110 seconds
[2023-04-21T22:21:50.933+0000] {processor.py:153} INFO - Started process (PID=1172) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:50.936+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:21:50.937+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:21:50.937+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:51.047+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:21:50.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:21:51.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:21:51.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.149 seconds
[2023-04-21T22:22:21.544+0000] {processor.py:153} INFO - Started process (PID=1216) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:21.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:22:21.547+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:22:21.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:21.598+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:22:21.589+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:22:21.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:21.619+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.078 seconds
[2023-04-21T22:22:51.761+0000] {processor.py:153} INFO - Started process (PID=1280) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:51.764+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:22:51.765+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:22:51.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:51.861+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:22:51.845+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:22:51.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:22:51.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.129 seconds
[2023-04-21T22:23:22.057+0000] {processor.py:153} INFO - Started process (PID=1324) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:22.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:23:22.063+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:23:22.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:22.161+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:23:22.148+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:23:22.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:22.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.137 seconds
[2023-04-21T22:23:52.592+0000] {processor.py:153} INFO - Started process (PID=1377) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:52.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:23:52.595+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:23:52.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:52.678+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:23:52.655+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:23:52.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:23:52.714+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.126 seconds
[2023-04-21T22:24:22.965+0000] {processor.py:153} INFO - Started process (PID=1431) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:22.968+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:24:22.970+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:24:22.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:23.072+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:24:23.060+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:24:23.077+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:23.098+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.136 seconds
[2023-04-21T22:24:53.312+0000] {processor.py:153} INFO - Started process (PID=1475) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:53.315+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:24:53.316+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:24:53.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:53.383+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:24:53.370+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:24:53.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:24:53.408+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.099 seconds
[2023-04-21T22:25:23.638+0000] {processor.py:153} INFO - Started process (PID=1539) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:23.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:25:23.642+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:25:23.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:23.738+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:25:23.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:25:23.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:23.768+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.132 seconds
[2023-04-21T22:25:53.957+0000] {processor.py:153} INFO - Started process (PID=1583) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:53.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:25:53.962+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:25:53.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:54.032+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:25:54.021+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:25:54.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:25:54.056+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-21T22:26:24.661+0000] {processor.py:153} INFO - Started process (PID=1647) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:24.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:26:24.667+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:26:24.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:24.723+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:26:24.712+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:26:24.728+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:24.793+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.134 seconds
[2023-04-21T22:26:54.972+0000] {processor.py:153} INFO - Started process (PID=1691) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:54.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:26:54.977+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:26:54.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:55.035+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:26:55.026+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:26:55.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:26:55.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-04-21T22:27:25.207+0000] {processor.py:153} INFO - Started process (PID=1754) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:25.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:27:25.211+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:27:25.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:25.299+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:27:25.284+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:27:25.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:25.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.123 seconds
[2023-04-21T22:27:55.983+0000] {processor.py:153} INFO - Started process (PID=1798) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:55.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:27:55.987+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:27:55.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:56.059+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:27:56.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:27:56.066+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:27:56.087+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.109 seconds
[2023-04-21T22:28:26.383+0000] {processor.py:153} INFO - Started process (PID=1862) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:26.387+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:28:26.388+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:28:26.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:26.482+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:28:26.462+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:28:26.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:26.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.137 seconds
[2023-04-21T22:28:56.931+0000] {processor.py:153} INFO - Started process (PID=1906) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:56.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:28:56.935+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:28:56.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:56.999+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:28:56.989+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:28:57.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:28:57.024+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.096 seconds
[2023-04-21T22:29:27.896+0000] {processor.py:153} INFO - Started process (PID=1950) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:27.899+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:29:27.900+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:29:27.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:27.979+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:29:27.965+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:29:27.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:28.008+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.114 seconds
[2023-04-21T22:29:58.778+0000] {processor.py:153} INFO - Started process (PID=2013) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:58.781+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:29:58.784+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:29:58.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:58.839+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:29:58.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:29:58.842+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:29:58.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.087 seconds
[2023-04-21T22:30:29.343+0000] {processor.py:153} INFO - Started process (PID=2057) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:29.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:30:29.348+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:30:29.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:29.456+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:30:29.438+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:30:29.462+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:29.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.204 seconds
[2023-04-21T22:30:59.708+0000] {processor.py:153} INFO - Started process (PID=2120) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:59.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:30:59.712+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:30:59.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:59.782+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:30:59.770+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:30:59.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:30:59.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.100 seconds
[2023-04-21T22:31:30.043+0000] {processor.py:153} INFO - Started process (PID=2164) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:31:30.045+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:31:30.046+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:31:30.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:31:30.094+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:31:30.087+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:31:30.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:31:30.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.077 seconds
[2023-04-21T22:32:00.243+0000] {processor.py:153} INFO - Started process (PID=2228) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:00.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:32:00.249+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:32:00.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:00.324+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:32:00.313+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:32:00.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:00.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.108 seconds
[2023-04-21T22:32:30.565+0000] {processor.py:153} INFO - Started process (PID=2273) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:30.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:32:30.571+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:32:30.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:30.661+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:32:30.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:32:30.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:32:30.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.124 seconds
[2023-04-21T22:33:00.803+0000] {processor.py:153} INFO - Started process (PID=2337) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:00.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:33:00.806+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:33:00.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:00.861+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:33:00.853+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:33:00.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:00.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.087 seconds
[2023-04-21T22:33:31.413+0000] {processor.py:153} INFO - Started process (PID=2381) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:31.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:33:31.416+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:33:31.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:31.476+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:33:31.466+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:33:31.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:33:31.501+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.093 seconds
[2023-04-21T22:34:01.693+0000] {processor.py:153} INFO - Started process (PID=2434) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:01.695+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:34:01.697+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:34:01.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:01.746+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:34:01.737+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:34:01.750+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:01.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.081 seconds
[2023-04-21T22:34:32.164+0000] {processor.py:153} INFO - Started process (PID=2489) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:32.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:34:32.170+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:34:32.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:32.265+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:34:32.256+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:34:32.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:34:32.287+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.126 seconds
[2023-04-21T22:35:03.088+0000] {processor.py:153} INFO - Started process (PID=2541) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:03.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:35:03.110+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:35:03.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:03.157+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:35:03.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:35:03.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:03.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.098 seconds
[2023-04-21T22:35:33.402+0000] {processor.py:153} INFO - Started process (PID=2598) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:33.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:35:33.408+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:35:33.408+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:33.488+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:35:33.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:35:33.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:35:33.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.112 seconds
[2023-04-21T22:36:03.638+0000] {processor.py:153} INFO - Started process (PID=2643) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:03.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:36:03.642+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:36:03.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:03.701+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:36:03.692+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:36:03.706+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:03.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.090 seconds
[2023-04-21T22:36:34.008+0000] {processor.py:153} INFO - Started process (PID=2707) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:34.011+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:36:34.013+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:36:34.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:34.141+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:36:34.122+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:36:34.150+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:36:34.171+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.166 seconds
[2023-04-21T22:37:04.314+0000] {processor.py:153} INFO - Started process (PID=2751) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:04.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:37:04.323+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:37:04.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:04.387+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:37:04.376+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:37:04.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:04.412+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-21T22:37:34.590+0000] {processor.py:153} INFO - Started process (PID=2803) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:34.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:37:34.594+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:37:34.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:34.666+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:37:34.647+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:37:34.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:37:34.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.116 seconds
[2023-04-21T22:38:05.045+0000] {processor.py:153} INFO - Started process (PID=2860) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:05.048+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:38:05.050+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:38:05.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:05.124+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:38:05.110+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:38:05.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:05.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.107 seconds
[2023-04-21T22:38:35.473+0000] {processor.py:153} INFO - Started process (PID=2905) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:35.476+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:38:35.477+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:38:35.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:35.534+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:38:35.522+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:38:35.541+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:38:35.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.092 seconds
[2023-04-21T22:39:05.783+0000] {processor.py:153} INFO - Started process (PID=2968) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:05.785+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:39:05.787+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:39:05.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:05.842+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:39:05.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:39:05.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:05.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.090 seconds
[2023-04-21T22:39:36.086+0000] {processor.py:153} INFO - Started process (PID=3013) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:36.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:39:36.093+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:39:36.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:36.147+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:39:36.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:39:36.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:39:36.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.089 seconds
[2023-04-21T22:40:06.339+0000] {processor.py:153} INFO - Started process (PID=3077) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:06.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:40:06.346+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:40:06.345+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:06.460+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:40:06.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:40:06.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:06.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.158 seconds
[2023-04-21T22:40:36.882+0000] {processor.py:153} INFO - Started process (PID=3121) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:36.887+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:40:36.888+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:40:36.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:36.963+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:40:36.952+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:40:36.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:40:36.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.110 seconds
[2023-04-21T22:41:07.746+0000] {processor.py:153} INFO - Started process (PID=3185) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:07.750+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:41:07.752+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:41:07.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:07.847+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:41:07.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:41:07.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:07.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.154 seconds
[2023-04-21T22:41:38.649+0000] {processor.py:153} INFO - Started process (PID=3229) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:38.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:41:38.654+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:41:38.654+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:38.865+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:41:38.748+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:41:38.915+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:41:38.945+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.302 seconds
[2023-04-21T22:42:09.024+0000] {processor.py:153} INFO - Started process (PID=3273) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:09.027+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:42:09.028+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:42:09.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:09.093+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:42:09.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:42:09.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:09.115+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.094 seconds
[2023-04-21T22:42:39.411+0000] {processor.py:153} INFO - Started process (PID=3337) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:39.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:42:39.416+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:42:39.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:39.485+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:42:39.454+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:42:39.499+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:42:39.523+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.114 seconds
[2023-04-21T22:43:10.239+0000] {processor.py:153} INFO - Started process (PID=3381) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:10.242+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:43:10.243+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:43:10.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:10.312+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:43:10.298+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:43:10.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:10.339+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.103 seconds
[2023-04-21T22:43:41.100+0000] {processor.py:153} INFO - Started process (PID=3446) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:41.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:43:41.106+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:43:41.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:41.185+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:43:41.164+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:43:41.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:43:41.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.111 seconds
[2023-04-21T22:44:11.339+0000] {processor.py:153} INFO - Started process (PID=3490) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:11.341+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:44:11.343+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:44:11.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:11.417+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:44:11.404+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:44:11.423+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:11.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.114 seconds
[2023-04-21T22:44:41.525+0000] {processor.py:153} INFO - Started process (PID=3555) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:41.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:44:41.529+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:44:41.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:41.595+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:44:41.583+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:44:41.600+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:44:41.619+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.097 seconds
[2023-04-21T22:45:12.019+0000] {processor.py:153} INFO - Started process (PID=3599) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:12.023+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:45:12.025+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:45:12.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:12.087+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:45:12.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:45:12.090+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:12.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.092 seconds
[2023-04-21T22:45:42.388+0000] {processor.py:153} INFO - Started process (PID=3662) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:42.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:45:42.393+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:45:42.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:42.446+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:45:42.437+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:45:42.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:45:42.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.082 seconds
[2023-04-21T22:46:13.144+0000] {processor.py:153} INFO - Started process (PID=3706) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:13.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:46:13.151+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:46:13.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:13.261+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:46:13.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:46:13.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:13.306+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.165 seconds
[2023-04-21T22:46:43.643+0000] {processor.py:153} INFO - Started process (PID=3769) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:43.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:46:43.649+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:46:43.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:43.718+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:46:43.707+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:46:43.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:46:43.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-21T22:47:13.867+0000] {processor.py:153} INFO - Started process (PID=3813) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:13.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:47:13.872+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:47:13.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:13.935+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:47:13.924+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:47:13.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:13.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.096 seconds
[2023-04-21T22:47:44.207+0000] {processor.py:153} INFO - Started process (PID=3877) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:44.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:47:44.210+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:47:44.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:44.314+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:47:44.288+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:47:44.325+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:47:44.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.148 seconds
[2023-04-21T22:48:14.541+0000] {processor.py:153} INFO - Started process (PID=3921) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:14.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:48:14.545+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:48:14.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:14.601+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:48:14.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:48:14.605+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:14.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.087 seconds
[2023-04-21T22:48:44.848+0000] {processor.py:153} INFO - Started process (PID=3974) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:44.851+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:48:44.852+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:48:44.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:44.904+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:48:44.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:48:44.909+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:48:44.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.083 seconds
[2023-04-21T22:49:15.282+0000] {processor.py:153} INFO - Started process (PID=4029) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:15.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:49:15.287+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:49:15.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:15.346+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:49:15.334+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:49:15.352+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:15.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.094 seconds
[2023-04-21T22:49:45.801+0000] {processor.py:153} INFO - Started process (PID=4071) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:45.804+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:49:45.805+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:49:45.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:45.871+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:49:45.859+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:49:45.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:49:45.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.096 seconds
[2023-04-21T22:50:15.970+0000] {processor.py:153} INFO - Started process (PID=4135) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:15.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:50:15.974+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:50:15.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:16.049+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:50:16.022+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:50:16.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:16.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.105 seconds
[2023-04-21T22:50:46.347+0000] {processor.py:153} INFO - Started process (PID=4179) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:46.350+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:50:46.352+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:50:46.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:46.421+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:50:46.411+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:50:46.425+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:50:46.445+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.101 seconds
[2023-04-21T22:51:16.772+0000] {processor.py:153} INFO - Started process (PID=4243) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:16.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:51:16.779+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:51:16.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:16.842+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:51:16.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:51:16.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:16.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.098 seconds
[2023-04-21T22:51:47.311+0000] {processor.py:153} INFO - Started process (PID=4287) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:47.313+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:51:47.315+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:51:47.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:47.387+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:51:47.374+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:51:47.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:51:47.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.104 seconds
[2023-04-21T22:52:17.655+0000] {processor.py:153} INFO - Started process (PID=4351) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:17.665+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:52:17.666+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:52:17.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:17.738+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:52:17.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:52:17.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:17.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.111 seconds
[2023-04-21T22:52:48.083+0000] {processor.py:153} INFO - Started process (PID=4394) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:48.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:52:48.089+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:52:48.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:48.206+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:52:48.190+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:52:48.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:52:48.231+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.151 seconds
[2023-04-21T22:53:18.514+0000] {processor.py:153} INFO - Started process (PID=4458) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:18.518+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:53:18.519+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:53:18.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:18.613+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:53:18.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:53:18.618+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:18.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.126 seconds
[2023-04-21T22:53:49.443+0000] {processor.py:153} INFO - Started process (PID=4501) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:49.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:53:49.448+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:53:49.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:49.517+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:53:49.506+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:53:49.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:53:49.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.100 seconds
[2023-04-21T22:54:19.789+0000] {processor.py:153} INFO - Started process (PID=4564) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:19.794+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:54:19.796+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:54:19.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:19.948+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:54:19.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:54:19.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:19.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.191 seconds
[2023-04-21T22:54:50.274+0000] {processor.py:153} INFO - Started process (PID=4607) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:50.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:54:50.278+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:54:50.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:50.359+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:54:50.349+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:54:50.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:54:50.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.112 seconds
[2023-04-21T22:55:20.781+0000] {processor.py:153} INFO - Started process (PID=4672) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:20.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:55:20.787+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:55:20.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:20.923+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:55:20.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:55:20.934+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:20.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.177 seconds
[2023-04-21T22:55:51.604+0000] {processor.py:153} INFO - Started process (PID=4716) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:51.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:55:51.608+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:55:51.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:51.660+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:55:51.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:55:51.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:55:51.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.080 seconds
[2023-04-21T22:56:22.092+0000] {processor.py:153} INFO - Started process (PID=4780) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:22.094+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:56:22.095+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:56:22.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:22.159+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:56:22.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:56:22.164+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:22.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.091 seconds
[2023-04-21T22:56:52.699+0000] {processor.py:153} INFO - Started process (PID=4824) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:52.703+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:56:52.705+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:56:52.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:52.780+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:56:52.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:56:52.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:56:52.805+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.109 seconds
[2023-04-21T22:57:23.057+0000] {processor.py:153} INFO - Started process (PID=4888) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:23.059+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:57:23.060+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:57:23.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:23.115+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:57:23.105+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:57:23.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:23.138+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.084 seconds
[2023-04-21T22:57:53.436+0000] {processor.py:153} INFO - Started process (PID=4932) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:53.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:57:53.440+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:57:53.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:53.493+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:57:53.485+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:57:53.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:57:53.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.082 seconds
[2023-04-21T22:58:23.643+0000] {processor.py:153} INFO - Started process (PID=4996) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:23.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:58:23.648+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:58:23.647+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:23.699+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:58:23.690+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:58:23.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:23.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.083 seconds
[2023-04-21T22:58:54.234+0000] {processor.py:153} INFO - Started process (PID=5040) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:54.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:58:54.240+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:58:54.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:54.312+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:58:54.288+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:58:54.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:58:54.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.114 seconds
[2023-04-21T22:59:24.444+0000] {processor.py:153} INFO - Started process (PID=5104) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:24.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:59:24.449+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:59:24.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:24.509+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:59:24.497+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:59:24.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:24.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.095 seconds
[2023-04-21T22:59:54.950+0000] {processor.py:153} INFO - Started process (PID=5148) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:54.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T22:59:54.953+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:59:54.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:55.042+0000] {logging_mixin.py:137} INFO - [2023-04-21T22:59:55.016+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T22:59:55.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T22:59:55.077+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.130 seconds
[2023-04-21T23:00:25.850+0000] {processor.py:153} INFO - Started process (PID=5212) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:25.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T23:00:25.855+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:00:25.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:26.029+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:00:26.002+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T23:00:26.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:26.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.215 seconds
[2023-04-21T23:00:56.664+0000] {processor.py:153} INFO - Started process (PID=5256) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:56.668+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T23:00:56.670+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:00:56.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:56.724+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:00:56.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T23:00:56.728+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:00:56.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.087 seconds
[2023-04-21T23:01:27.128+0000] {processor.py:153} INFO - Started process (PID=5309) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:27.130+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T23:01:27.131+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:01:27.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:27.188+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:01:27.177+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T23:01:27.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:27.210+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.085 seconds
[2023-04-21T23:01:57.520+0000] {processor.py:153} INFO - Started process (PID=5364) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:57.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T23:01:57.526+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:01:57.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:57.766+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:01:57.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T23:01:57.785+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:01:57.804+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.287 seconds
[2023-04-21T23:02:28.169+0000] {processor.py:153} INFO - Started process (PID=5409) to work on /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:02:28.171+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/test/test_forexdag_definition.py for tasks to queue
[2023-04-21T23:02:28.172+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:02:28.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:02:28.448+0000] {logging_mixin.py:137} INFO - [2023-04-21T23:02:28.429+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/test/test_forexdag_definition.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test/test_forexdag_definition.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2023-04-21T23:02:28.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/test/test_forexdag_definition.py
[2023-04-21T23:02:28.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/test/test_forexdag_definition.py took 0.318 seconds
